### ISSUE TITLE
ungzip on the fly if client doesn't accept gzip encoding

### ISSUE THREAD

**Issue by rjmunro** [code42day/connect-gzip-static#11]
Rather than have to keep a unzipped copy of every static file on the server, and ensure it is kept in sync, could the server dynamically uncompress the gziped file if the 'Accept-Encoding' header doesn't accept gzip? This may even be faster in cases where the disk is the bottleneck - ungzipping doesn't require that much cpu or memory.

**Comment by pirxpilot** [comment]
So basically an evil twin of [compress midleware](https://github.com/expressjs/compression) ;-)
Quite frankly I don't think it has a place here. `connnect-gzip-static` is meant to be super simple (and thus fast), at the price of using extra disk storage. It's also meant to be used if your build process already takes care of compressing files.
That of course that should not discourage you from forking and publishing your own version.
