### ISSUE TITLE
enhancement: Only cache/serve when smaller than original

### ISSUE THREAD

**Issue by sspilleman** [code42day/connect-gzip-static#12]
Hi,

Like you module. Can I suggest an enhancement, which is the following:

As you know gzipping doesn't alway result in smaller files, so only cache and serve when the gzipped file is actually smaller than the filesize of the original file..

I modified your code in the following manner to allow this:

added:
var fs = require('fs');

changed:
function createCache(root) {
    var cache = Object.create(null);
    find.fileSync(/.gz$/, root).forEach(function(file) {
        var originalFilename = file.slice(0, file.lastIndexOf("."));
        if (fs.statSync(file).size < fs.statSync(originalFilename).size) {
            debug("caching:", file);
            cache[file] = true;
        } else {
            debug("skipping:", file);
        }
    });
    debug('Found %d compressed files', Object.keys(cache).length);
    return cache;
}

Greetz,

Sander

**Comment by pirxpilot** [comment]
Thanks! The assumption here is that build process (and not this module) is responsible for compressing files, so it kind of follows that the build process would be responsible for skipping edge cases that would result in a compressed file bigger than original. So I am just not sure this is worth it.
Then again - if this is something you see and you cannot modify the build process go ahead and create your own fork. I'll have another look.

**Comment by sspilleman** [comment]
I agree, it's just a point of view… My counter argument is this though: The build process “just” creates gzipped files for *all* files…… And I’m using your module to decide which files are going to be served. Thats the point of this module right? To make a decision to serve a different file than he one being requested? In that case, the decision should incorporate the fact to serve the original *requested* file if that turn outs to be smaller than the gzipped one….

Sander

**Comment by pirxpilot** [comment]
Sure. I am not trying to argue. Go ahead: create a fork, implement it, publish your own module and/or send a pull requests with tests.
